/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project.Entreprise;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.border.Border;

/**
 *
 * @author LAULAU
 */
public class ChoiceMaterials extends javax.swing.JFrame {
    // Définition des Propriétés
    String typeOfProduct = "Steel";
    String reference = "";
    /**
     * Creates new form DialogAccount
     * @param ref
     */
    public ChoiceMaterials(String ref) {
        initComponents();
        menuBox.setBackground(new Color(255,233,197,220));
        steel.setBackground(new Color(255,233,197,220));
        wood.setBackground(new Color(255,233,197,220));
        plastic.setBackground(new Color(255,233,197,220));
        glass.setBackground(new Color(255,233,197,220));
        
        // Afficher le numéro de la référence du produit dans le cadre du composant
        Border framework = BorderFactory.createTitledBorder("    Reference :   " + ref + "   "   );
        menuBox.setBorder(framework);
        setBounds(500,130,650,635);
        setVisible(true);
        
        //Afficher une image en fond de fenêtre
        ImageIcon iconPhoto = new ImageIcon ("C:\\Users\\LAULAU\\Documents\\"
                            + "NetBeansProjects\\Entreprise\\Photos\\Stock\\"
                            + "distributeurs2ChoiceMaterials.png");
        backgroundPhoto.setIcon(iconPhoto);
  
        // Création d'un groupe de boutons 
        createBoxGroup();
        reference = ref;   
    }
    
    private void createBoxGroup(){
        referenceGroup.add(steel);
        referenceGroup.add(plastic);
        referenceGroup.add(wood);
        referenceGroup.add(glass);
        steel.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        referenceGroup = new javax.swing.ButtonGroup();
        menuBox = new javax.swing.JPanel();
        steel = new javax.swing.JCheckBox();
        plastic = new javax.swing.JCheckBox();
        wood = new javax.swing.JCheckBox();
        glass = new javax.swing.JCheckBox();
        enteredQuantity = new javax.swing.JTextField();
        quantityLabel = new javax.swing.JLabel();
        okBtn = new javax.swing.JButton();
        stySecurityStockLabel = new javax.swing.JLabel();
        enteredSecurityStock = new javax.swing.JTextField();
        backgroundPhoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Choice Product");
        setResizable(false);
        getContentPane().setLayout(null);

        menuBox.setBackground(new java.awt.Color(255, 233, 197));
        menuBox.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ressource", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 18)), "Reference : ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 18))); // NOI18N
        menuBox.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        steel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        steel.setText("   Steel");
        steel.setToolTipText("Choose a Product");
        steel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        steel.setOpaque(false);
        steel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                steelActionPerformed(evt);
            }
        });

        plastic.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        plastic.setText("   Plastic");
        plastic.setToolTipText("Choose a Product");
        plastic.setOpaque(false);
        plastic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plasticActionPerformed(evt);
            }
        });

        wood.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        wood.setText("   Wood");
        wood.setToolTipText("Choose a Product");
        wood.setOpaque(false);
        wood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                woodActionPerformed(evt);
            }
        });

        glass.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        glass.setText("   Glass");
        glass.setToolTipText("Choose a Product");
        glass.setOpaque(false);
        glass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                glassActionPerformed(evt);
            }
        });

        enteredQuantity.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        enteredQuantity.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        enteredQuantity.setText("0");
        enteredQuantity.setToolTipText("Indicate the Initial Quantity");

        quantityLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        quantityLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        quantityLabel.setText("Initial Quantity");

        okBtn.setBackground(new java.awt.Color(153, 153, 153));
        okBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        okBtn.setText("OK");
        okBtn.setToolTipText("Click to validate");
        okBtn.setBorder(null);
        okBtn.setMaximumSize(new java.awt.Dimension(50, 25));
        okBtn.setMinimumSize(new java.awt.Dimension(50, 19));
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        stySecurityStockLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        stySecurityStockLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        stySecurityStockLabel.setText("Security Stock");

        enteredSecurityStock.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        enteredSecurityStock.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        enteredSecurityStock.setText("0");
        enteredSecurityStock.setToolTipText("Indicate The Security Stock Point");

        javax.swing.GroupLayout menuBoxLayout = new javax.swing.GroupLayout(menuBox);
        menuBox.setLayout(menuBoxLayout);
        menuBoxLayout.setHorizontalGroup(
            menuBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBoxLayout.createSequentialGroup()
                .addGroup(menuBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuBoxLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(stySecurityStockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuBoxLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(menuBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantityLabel)
                            .addComponent(plastic, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(steel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(54, 54, 54)
                .addGroup(menuBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(menuBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(enteredQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(enteredSecurityStock, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(glass)
                        .addComponent(wood)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        menuBoxLayout.setVerticalGroup(
            menuBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(steel)
                    .addComponent(wood))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menuBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(glass)
                    .addComponent(plastic))
                .addGap(38, 38, 38)
                .addGroup(menuBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enteredQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(menuBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enteredSecurityStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stySecurityStockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        getContentPane().add(menuBox);
        menuBox.setBounds(130, 200, 390, 300);

        backgroundPhoto.setBackground(new java.awt.Color(190, 190, 190));
        backgroundPhoto.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(backgroundPhoto);
        backgroundPhoto.setBounds(0, 0, 660, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void steelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_steelActionPerformed
        // Initialiser le type du product à "Steel"
        typeOfProduct = "Steel";
    }//GEN-LAST:event_steelActionPerformed

    private void woodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_woodActionPerformed
        // Initialiser le type du product à "Wood"
        typeOfProduct = "Wood";
    }//GEN-LAST:event_woodActionPerformed

    private void plasticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plasticActionPerformed
        // Initialiser le type du product à "Plastic"
        typeOfProduct = "Plastic";
    }//GEN-LAST:event_plasticActionPerformed

    private void glassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_glassActionPerformed
        // Initialiser le type du product à "Glass"
        typeOfProduct = "Glass";
    }//GEN-LAST:event_glassActionPerformed

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        // Récupérer "initialQuantity" déposée dans le champ de saisi
        double initialQuantity = Double.parseDouble(enteredQuantity.getText());
        // Récupérer "securityStockPt" déposée dans le champ de saisi
        double securityStockPt = Double.parseDouble(enteredSecurityStock.getText());
        // Créer un objet de type Inventory à l'aide de son constructeur
        Inventory aStock = new Inventory(reference, typeOfProduct, initialQuantity, securityStockPt);
        // aStock.displayReference();
        // Enregistrer la réference daans un fichier objet
        // dont le nom porte la référence du produit suivi de l'extension .dat
        MaterialsFile mf = new MaterialsFile();
        mf.open("Product" + reference + ".dat","W");
        mf.write(aStock);
        mf.close();

        // Fermer la fenêtre sans fermer l'application
        this.dispose();
    }//GEN-LAST:event_okBtnActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundPhoto;
    private javax.swing.JTextField enteredQuantity;
    private javax.swing.JTextField enteredSecurityStock;
    private javax.swing.JCheckBox glass;
    private javax.swing.JPanel menuBox;
    private javax.swing.JButton okBtn;
    private javax.swing.JCheckBox plastic;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.ButtonGroup referenceGroup;
    private javax.swing.JCheckBox steel;
    private javax.swing.JLabel stySecurityStockLabel;
    private javax.swing.JCheckBox wood;
    // End of variables declaration//GEN-END:variables
}
