/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project.Entreprise;

import java.text.ParseException;

/**
 *
 * @author LAULAU
 */
public class EditLogisticsLine extends javax.swing.JPanel {

    /**
     * Creates new form EditLine
     * @param tmp
     * @throws java.text.ParseException
     */
    public EditLogisticsLine(LogisticsLine tmp) throws ParseException {
        initComponents();
        setBounds(0, 0, 200, 20);
        setVisible(true);
        // Afficher la raison pour laquelle la transaction se fait 
        // de l'objet LogisticsLine dans le composant nommé reasonLabel
        reasonLabel.setText(tmp.getReason());
        reasonLabel.setBounds(0,0,200,20);
        // Afficher le type de transaction faite de l'objet 
        // LogisticsLine dans le composant nommé transactionLabel
        transactionLabel.setText(tmp.getTransaction());
        transactionLabel.setBounds(0,0,200,20);
        // Afficher la date de la transaction de l'objet 
        // LogisticsLine dans le composant nommé dateLabel
        dateLabel.setText(tmp.getDate());
        dateLabel.setBounds(0,0,200,20);
        // Afficher la quantité de la transaction de l'objet 
        // LogisticsLine dans le composant nommé quantityLabel
        quantityLabel.setText(Double.toString(tmp.getLogisticsQuantity()));
        quantityLabel.setBounds(0,0,200,20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reasonLabel = new javax.swing.JLabel();
        transactionLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153)));
        setToolTipText("");
        setAlignmentX(0.0F);
        setAlignmentY(0.1F);
        setMinimumSize(new java.awt.Dimension(3924, 17));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 21));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.GridLayout(1, 4));

        reasonLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        reasonLabel.setText("Reason : ");
        reasonLabel.setIconTextGap(1);
        reasonLabel.setMaximumSize(new java.awt.Dimension(980, 20));
        reasonLabel.setMinimumSize(null);
        reasonLabel.setPreferredSize(new java.awt.Dimension(980, 17));
        add(reasonLabel);

        transactionLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        transactionLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        transactionLabel.setText("Transaction : ");
        transactionLabel.setIconTextGap(1);
        transactionLabel.setMaximumSize(new java.awt.Dimension(980, 20));
        transactionLabel.setMinimumSize(null);
        transactionLabel.setPreferredSize(new java.awt.Dimension(980, 17));
        add(transactionLabel);

        dateLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dateLabel.setText("Date : ");
        dateLabel.setAlignmentY(0.1F);
        dateLabel.setIconTextGap(1);
        dateLabel.setMaximumSize(new java.awt.Dimension(980, 20));
        dateLabel.setMinimumSize(new java.awt.Dimension(980, 20));
        dateLabel.setPreferredSize(new java.awt.Dimension(980, 17));
        add(dateLabel);

        quantityLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        quantityLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        quantityLabel.setText("Quantity :  ");
        quantityLabel.setIconTextGap(1);
        quantityLabel.setMaximumSize(new java.awt.Dimension(980, 20));
        quantityLabel.setMinimumSize(null);
        quantityLabel.setPreferredSize(new java.awt.Dimension(980, 17));
        add(quantityLabel);

        getAccessibleContext().setAccessibleName("EditLogLine");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JLabel reasonLabel;
    private javax.swing.JLabel transactionLabel;
    // End of variables declaration//GEN-END:variables
}
