/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project.Entreprise;

import java.awt.Color;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author LAULAU
 */
public class Main extends javax.swing.JFrame {
    // Définition des propriétés
     String reference="";
     String actionChoice = "Create a new Reference";
    
     /**
     * Creates new form Main
     */
    public Main() { 
        initComponents();
        this.setBounds(460,460,630, 470);
        bigBox.setBackground(new Color(221,190,141,170));
        infoMenu.setBackground(new Color(190,190,190,210));
        referenceMenu.setBackground(new Color(190,190,190,210));
        
        // Affichage d'une image en fond de fenêtre
        ImageIcon iconPhoto = new ImageIcon("C:\\Users\\LAULAU\\Documents\\"
              + "NetBeansProjects\\Entreprise\\Photos\\Stock\\storageMain.png");
        backgroundPhoto.setIcon(iconPhoto);
        
        // Créer un groupe de boutons
        createGroupBox();
      
        
    }
    private void createGroupBox() {   
         buttonGroup.add(createRdButton);
         buttonGroup.add(addRdButton);
         buttonGroup.add(editRdButton);
         createRdButton.setSelected(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        bigBox = new javax.swing.JPanel();
        infoMenu = new javax.swing.JPanel();
        createRdButton = new javax.swing.JRadioButton();
        addRdButton = new javax.swing.JRadioButton();
        editRdButton = new javax.swing.JRadioButton();
        referenceMenu = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        enteredReference = new javax.swing.JTextField();
        backgroundPhoto = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stock Manager");
        setBackground(new java.awt.Color(190, 190, 190));
        setResizable(false);
        getContentPane().setLayout(null);

        bigBox.setBackground(new java.awt.Color(221, 190, 141));

        infoMenu.setBackground(new java.awt.Color(190, 190, 190));
        infoMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)), "Info Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14))); // NOI18N
        infoMenu.setToolTipText("Press a Button to do a choice");
        infoMenu.setPreferredSize(new java.awt.Dimension(274, 113));

        createRdButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        createRdButton.setText("Create a new Reference");
        createRdButton.setToolTipText("");
        createRdButton.setContentAreaFilled(false);
        createRdButton.setOpaque(true);
        createRdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createRdButtonActionPerformed(evt);
            }
        });

        addRdButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addRdButton.setText("Add a Logistical Action");
        addRdButton.setContentAreaFilled(false);
        addRdButton.setOpaque(true);
        addRdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRdButtonActionPerformed(evt);
            }
        });

        editRdButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        editRdButton.setText("Edit the Logistic(s) Line(s)");
        editRdButton.setContentAreaFilled(false);
        editRdButton.setOpaque(true);
        editRdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRdButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout infoMenuLayout = new javax.swing.GroupLayout(infoMenu);
        infoMenu.setLayout(infoMenuLayout);
        infoMenuLayout.setHorizontalGroup(
            infoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoMenuLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(infoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addRdButton, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editRdButton, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createRdButton, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        infoMenuLayout.setVerticalGroup(
            infoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createRdButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addRdButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editRdButton)
                .addContainerGap())
        );

        referenceMenu.setBackground(new java.awt.Color(190, 190, 190));
        referenceMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)), "Reference", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14))); // NOI18N

        okButton.setBackground(new java.awt.Color(153, 153, 153));
        okButton.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        okButton.setText("OK");
        okButton.setToolTipText("Click to validate");
        okButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        enteredReference.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        enteredReference.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        enteredReference.setToolTipText("Indicate a Reference of  6 characters !");

        javax.swing.GroupLayout referenceMenuLayout = new javax.swing.GroupLayout(referenceMenu);
        referenceMenu.setLayout(referenceMenuLayout);
        referenceMenuLayout.setHorizontalGroup(
            referenceMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(referenceMenuLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(enteredReference, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        referenceMenuLayout.setVerticalGroup(
            referenceMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(referenceMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(referenceMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(enteredReference)
                    .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bigBoxLayout = new javax.swing.GroupLayout(bigBox);
        bigBox.setLayout(bigBoxLayout);
        bigBoxLayout.setHorizontalGroup(
            bigBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bigBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bigBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addComponent(referenceMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        bigBoxLayout.setVerticalGroup(
            bigBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bigBoxLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(infoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(referenceMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(bigBox);
        bigBox.setBounds(100, 150, 420, 240);

        backgroundPhoto.setBackground(new java.awt.Color(190, 190, 190));
        getContentPane().add(backgroundPhoto);
        backgroundPhoto.setBounds(0, 0, 620, 410);

        fileMenu.setText("File");
        fileMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        fileMenu.add(exit);

        menuBar.add(fileMenu);

        editMenu.setText("Edit");
        editMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
      // Récupérer la référence
      if ((enteredReference.getText()).length() == 6){
            reference = enteredReference.getText();
        
        // Si l'action est "Create a new Reference"
        if(actionChoice.equals("Create a new Reference")){
            // Ouvrir la boite de dialogue CompteDaliogue
            new ChoiceMaterials(reference);

        }
        // Si l'action est "Add a Logistical Action"
        else  if(actionChoice.equals("Add a Logistical Action")){
            // Lire le fichier associé à la référence
            MaterialsFile mf = new MaterialsFile();
            if (mf.open("Product" + reference + ".dat","R")) {
                // Si le fichier existe, 
                // stocker les informations lues dans un objet "aStock"
                Inventory aStock = mf.read();
                mf.close();
                // Ouvrir la boite de dialogue "LineCreation" 
                // en passant en paramètre les informations lues
                new LineCreation(aStock);
            }
            // Si le fichier n'existe pas, afficher un message d'alerte
            else new Message("The reference : ", reference ,
                    " Does not exist !","");
        }
        // Si l'action est "Edit the Logistic(s) Line(s)"
        else  if(actionChoice.equals("Edit the Logistic(s) Line(s)")){
            // Lire le fichier associé à la référence
            MaterialsFile mf = new MaterialsFile();
            if (mf.open("Product"+reference+".dat","R")){
               // Si le fichier existe, 
               // stocker les informations lues dans un objet "aStock"
               Inventory aStock = mf.read();
               mf.close();
                try {
                    // Ouvrir la boite de dialogue "EditMaterial" 
                    // en passant en paramètre les informations lues
                    new EditMaterial(aStock);
                } catch (ParseException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            // Si le fichier n'existe pas, afficher un message d'alerte
            else new Message("The reference : ", reference ,
                    " Does not exist !","");  
        }
      }  
      else if ((enteredReference.getText()).length() != 6)
            new Message("The Reference :",enteredReference.getText(),
                    "Must contain 6 characters !!!","");
      
    }//GEN-LAST:event_okButtonActionPerformed
      
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void editRdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRdButtonActionPerformed
        // Initialiser l'action à "Editer la référence voulue !"
        actionChoice = "Edit the Logistic(s) Line(s)";
    }//GEN-LAST:event_editRdButtonActionPerformed

    private void addRdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRdButtonActionPerformed
        // Initialiser l'action à "Ajouter une ligne logistique sur une référence !"
        actionChoice = "Add a Logistical Action";
    }//GEN-LAST:event_addRdButtonActionPerformed

    private void createRdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRdButtonActionPerformed
        // Initialiser l'action à "Create a new Reference !"
        actionChoice = "Create a new Reference";
    }//GEN-LAST:event_createRdButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
                new PresentationPage();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton addRdButton;
    private javax.swing.JLabel backgroundPhoto;
    private javax.swing.JPanel bigBox;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton createRdButton;
    private javax.swing.JMenu editMenu;
    private javax.swing.JRadioButton editRdButton;
    private javax.swing.JTextField enteredReference;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPanel infoMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel referenceMenu;
    // End of variables declaration//GEN-END:variables
}
