/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project.Entreprise;

/**
 *
 * @author LAULAU
 */
public class Message extends javax.swing.JFrame {

    /**
     * Creates new form Message
     */
     public Message(String mgeL, String refLog, String mgText, String mgText2) {
        this.setVisible(true);
        initComponents();
        this.setBounds(300, 300, 750, 450);
        //Affiche le contenu du premier paramètre dans le composant messageLog
        messageLog.setText(mgeL);
        //Affiche le contenu du deuxième paramètre dans le composant reference
        reference.setText(refLog);
        //Affiche le contenu du troisième paramètre dans le composant text
        text.setText(mgText);
        //Affiche le contenu du quatrième paramètre dans le composant text2
        text2.setText(mgText2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messageLog = new javax.swing.JLabel();
        reference = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        text2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Message :");

        messageLog.setBackground(new java.awt.Color(190, 190, 190));
        messageLog.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        messageLog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageLog.setText("The Reference :");

        reference.setBackground(new java.awt.Color(255, 255, 255));
        reference.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        reference.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        text.setBackground(new java.awt.Color(190, 190, 190));
        text.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        text.setForeground(new java.awt.Color(255, 0, 51));
        text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        text2.setBackground(new java.awt.Color(190, 190, 190));
        text2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        text2.setForeground(new java.awt.Color(255, 0, 51));
        text2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton1.setBackground(new java.awt.Color(190, 190, 190));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("OK");
        jButton1.setToolTipText("Click here to close this window and return about to the previous window");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reference, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(text2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(messageLog, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(messageLog, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reference, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Quitter le message sans quitter l'application
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel messageLog;
    private javax.swing.JLabel reference;
    private javax.swing.JLabel text;
    private javax.swing.JLabel text2;
    // End of variables declaration//GEN-END:variables
}
